// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWYCTN8XQOBVEVlDoaSs24l6l5gIUFiiI',
    appId: '1:243846470318:web:c927d0cc9c5e994724eb3f',
    messagingSenderId: '243846470318',
    projectId: 'eat-and-share-4f0a0',
    authDomain: 'eat-and-share-4f0a0.firebaseapp.com',
    storageBucket: 'eat-and-share-4f0a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04kJhOd-TRu93mLPLW8aCfa6XTUbz4zw',
    appId: '1:243846470318:android:df29d1e7d449e12224eb3f',
    messagingSenderId: '243846470318',
    projectId: 'eat-and-share-4f0a0',
    storageBucket: 'eat-and-share-4f0a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnE7ZG7O_-vf0zqsejuR_EKEL09kEtUiw',
    appId: '1:243846470318:ios:ac181d119e78c81724eb3f',
    messagingSenderId: '243846470318',
    projectId: 'eat-and-share-4f0a0',
    storageBucket: 'eat-and-share-4f0a0.appspot.com',
    iosBundleId: 'com.example.pree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnE7ZG7O_-vf0zqsejuR_EKEL09kEtUiw',
    appId: '1:243846470318:ios:ac181d119e78c81724eb3f',
    messagingSenderId: '243846470318',
    projectId: 'eat-and-share-4f0a0',
    storageBucket: 'eat-and-share-4f0a0.appspot.com',
    iosBundleId: 'com.example.pree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWYCTN8XQOBVEVlDoaSs24l6l5gIUFiiI',
    appId: '1:243846470318:web:9b7b76782a6b94f124eb3f',
    messagingSenderId: '243846470318',
    projectId: 'eat-and-share-4f0a0',
    authDomain: 'eat-and-share-4f0a0.firebaseapp.com',
    storageBucket: 'eat-and-share-4f0a0.appspot.com',
  );
}
